apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        name: Publish artifact
        with:
          name: "MyAppBE"
          version: "2.0.0-${{cloudbees.version}}"
          url: "docker.io/MyApp/MyAppBE:2.0.0-${{cloudbees.version}}"
          #digest: "sha256:5e0fa16466150c58f628dc6e6c40a9b07e3b3609d"
