apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppBE
      baseVersion: 2.1.0