apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  pre-prod:
    if: ${{ inputs.environment }} == "pre-prod"
    environment: pre-prod
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: ${{ inputs.artifactName }}
      artifactVersion: ${{ inputs.artifactVersion }}
      environment: ${{ inputs.environment }}
  prod:
    if: ${{ inputs.environment }} == "prod"
    environment: prod
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: ${{ inputs.artifactName }}
      artifactVersion: ${{ inputs.artifactVersion }}
      environment: ${{ inputs.environment }}
