apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  steps:
    deploy:
      uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
      with:
        artifactName: ${{ inputs.artifactName }}
        artifactVersions: ${{ inputs.artifactVersion }}
        environment: ${{ inputs.environment }}
